package com.moodtracker.ui.theme

import androidx.compose.ui.graphics.Color

// ========================================
// SERENITY THEME - Calming Blues/Purples
// ========================================

// Serenity Light
val serenity_light_primary = Color(0xFF667EEA)
val serenity_light_onPrimary = Color(0xFFFFFFFF)
val serenity_light_primaryContainer = Color(0xFFE0E7FF)
val serenity_light_onPrimaryContainer = Color(0xFF1A1B3D)
val serenity_light_secondary = Color(0xFF764BA2)
val serenity_light_onSecondary = Color(0xFFFFFFFF)
val serenity_light_secondaryContainer = Color(0xFFE8D4F8)
val serenity_light_onSecondaryContainer = Color(0xFF2D1B42)
val serenity_light_tertiary = Color(0xFF8B9FFF)
val serenity_light_onTertiary = Color(0xFFFFFFFF)
val serenity_light_tertiaryContainer = Color(0xFFE5EBFF)
val serenity_light_onTertiaryContainer = Color(0xFF1A1B3D)
val serenity_light_error = Color(0xFFEF4444)
val serenity_light_errorContainer = Color(0xFFFFE4E6)
val serenity_light_onError = Color(0xFFFFFFFF)
val serenity_light_onErrorContainer = Color(0xFF7F1D1D)
val serenity_light_background = Color(0xFFF8F9FF)
val serenity_light_onBackground = Color(0xFF1F2937)
val serenity_light_surface = Color(0xFFFFFFFF)
val serenity_light_onSurface = Color(0xFF1F2937)
val serenity_light_surfaceVariant = Color(0xFFF0F2FF)
val serenity_light_onSurfaceVariant = Color(0xFF6B7280)
val serenity_light_outline = Color(0xFFD1D5DB)
val serenity_light_inverseOnSurface = Color(0xFFF8F9FF)
val serenity_light_inverseSurface = Color(0xFF374151)
val serenity_light_inversePrimary = Color(0xFF8B9FFF)
val serenity_light_shadow = Color(0xFF000000)
val serenity_light_surfaceTint = Color(0xFF667EEA)
val serenity_light_outlineVariant = Color(0xFFE5E7EB)
val serenity_light_scrim = Color(0xFF000000)

// Serenity Dark
val serenity_dark_primary = Color(0xFF8B9FFF)
val serenity_dark_onPrimary = Color(0xFF1A1B3D)
val serenity_dark_primaryContainer = Color(0xFF5568D3)
val serenity_dark_onPrimaryContainer = Color(0xFFE0E7FF)
val serenity_dark_secondary = Color(0xFF9B6FCF)
val serenity_dark_onSecondary = Color(0xFF2D1B42)
val serenity_dark_secondaryContainer = Color(0xFF6B4B95)
val serenity_dark_onSecondaryContainer = Color(0xFFE8D4F8)
val serenity_dark_tertiary = Color(0xFFA5B4FF)
val serenity_dark_onTertiary = Color(0xFF1A1B3D)
val serenity_dark_tertiaryContainer = Color(0xFF6B7EE5)
val serenity_dark_onTertiaryContainer = Color(0xFFE5EBFF)
val serenity_dark_error = Color(0xFFFF6B6B)
val serenity_dark_errorContainer = Color(0xFFEF4444)
val serenity_dark_onError = Color(0xFF7F1D1D)
val serenity_dark_onErrorContainer = Color(0xFFFFE4E6)
val serenity_dark_background = Color(0xFF0F0F1E)
val serenity_dark_onBackground = Color(0xFFF9FAFB)
val serenity_dark_surface = Color(0xFF1A1A2E)
val serenity_dark_onSurface = Color(0xFFF9FAFB)
val serenity_dark_surfaceVariant = Color(0xFF242438)
val serenity_dark_onSurfaceVariant = Color(0xFF9CA3AF)
val serenity_dark_outline = Color(0xFF6B7280)
val serenity_dark_inverseOnSurface = Color(0xFF1A1A2E)
val serenity_dark_inverseSurface = Color(0xFFF9FAFB)
val serenity_dark_inversePrimary = Color(0xFF667EEA)
val serenity_dark_shadow = Color(0xFF000000)
val serenity_dark_surfaceTint = Color(0xFF8B9FFF)
val serenity_dark_outlineVariant = Color(0xFF4B5563)
val serenity_dark_scrim = Color(0xFF000000)

// ========================================
// SUNSET THEME - Warm Oranges/Pinks
// ========================================

// Sunset Light
val sunset_light_primary = Color(0xFFFF6B6B)
val sunset_light_onPrimary = Color(0xFFFFFFFF)
val sunset_light_primaryContainer = Color(0xFFFFE4E6)
val sunset_light_onPrimaryContainer = Color(0xFF3D1010)
val sunset_light_secondary = Color(0xFFFFB347)
val sunset_light_onSecondary = Color(0xFF3D2A10)
val sunset_light_secondaryContainer = Color(0xFFFFEDD5)
val sunset_light_onSecondaryContainer = Color(0xFF3D2A10)
val sunset_light_tertiary = Color(0xFFFF8787)
val sunset_light_onTertiary = Color(0xFFFFFFFF)
val sunset_light_tertiaryContainer = Color(0xFFFFE8E8)
val sunset_light_onTertiaryContainer = Color(0xFF3D1010)
val sunset_light_error = Color(0xFFDC2626)
val sunset_light_errorContainer = Color(0xFFFEE2E2)
val sunset_light_onError = Color(0xFFFFFFFF)
val sunset_light_onErrorContainer = Color(0xFF7F1D1D)
val sunset_light_background = Color(0xFFFFF5F5)
val sunset_light_onBackground = Color(0xFF1F2937)
val sunset_light_surface = Color(0xFFFFFFFF)
val sunset_light_onSurface = Color(0xFF1F2937)
val sunset_light_surfaceVariant = Color(0xFFFFF0F0)
val sunset_light_onSurfaceVariant = Color(0xFF6B7280)
val sunset_light_outline = Color(0xFFD1D5DB)
val sunset_light_inverseOnSurface = Color(0xFFFFF5F5)
val sunset_light_inverseSurface = Color(0xFF374151)
val sunset_light_inversePrimary = Color(0xFFFF8787)
val sunset_light_shadow = Color(0xFF000000)
val sunset_light_surfaceTint = Color(0xFFFF6B6B)
val sunset_light_outlineVariant = Color(0xFFE5E7EB)
val sunset_light_scrim = Color(0xFF000000)

// Sunset Dark
val sunset_dark_primary = Color(0xFFFF8787)
val sunset_dark_onPrimary = Color(0xFF3D1010)
val sunset_dark_primaryContainer = Color(0xFFE85555)
val sunset_dark_onPrimaryContainer = Color(0xFFFFE4E6)
val sunset_dark_secondary = Color(0xFFFFC670)
val sunset_dark_onSecondary = Color(0xFF3D2A10)
val sunset_dark_secondaryContainer = Color(0xFFE89F2F)
val sunset_dark_onSecondaryContainer = Color(0xFFFFEDD5)
val sunset_dark_tertiary = Color(0xFFFFA0A0)
val sunset_dark_onTertiary = Color(0xFF3D1010)
val sunset_dark_tertiaryContainer = Color(0xFFE86B6B)
val sunset_dark_onTertiaryContainer = Color(0xFFFFE8E8)
val sunset_dark_error = Color(0xFFFF6B6B)
val sunset_dark_errorContainer = Color(0xFFDC2626)
val sunset_dark_onError = Color(0xFF7F1D1D)
val sunset_dark_onErrorContainer = Color(0xFFFEE2E2)
val sunset_dark_background = Color(0xFF1A0E0E)
val sunset_dark_onBackground = Color(0xFFF9FAFB)
val sunset_dark_surface = Color(0xFF2A1515)
val sunset_dark_onSurface = Color(0xFFF9FAFB)
val sunset_dark_surfaceVariant = Color(0xFF3A1F1F)
val sunset_dark_onSurfaceVariant = Color(0xFF9CA3AF)
val sunset_dark_outline = Color(0xFF6B7280)
val sunset_dark_inverseOnSurface = Color(0xFF2A1515)
val sunset_dark_inverseSurface = Color(0xFFF9FAFB)
val sunset_dark_inversePrimary = Color(0xFFFF6B6B)
val sunset_dark_shadow = Color(0xFF000000)
val sunset_dark_surfaceTint = Color(0xFFFF8787)
val sunset_dark_outlineVariant = Color(0xFF4B5563)
val sunset_dark_scrim = Color(0xFF000000)

// ========================================
// FOREST THEME - Natural Greens
// ========================================

// Forest Light
val forest_light_primary = Color(0xFF2ECC71)
val forest_light_onPrimary = Color(0xFFFFFFFF)
val forest_light_primaryContainer = Color(0xFFD1FAE5)
val forest_light_onPrimaryContainer = Color(0xFF064E3B)
val forest_light_secondary = Color(0xFF3498DB)
val forest_light_onSecondary = Color(0xFFFFFFFF)
val forest_light_secondaryContainer = Color(0xFFDBEAFE)
val forest_light_onSecondaryContainer = Color(0xFF1E3A5F)
val forest_light_tertiary = Color(0xFF52D98D)
val forest_light_onTertiary = Color(0xFFFFFFFF)
val forest_light_tertiaryContainer = Color(0xFFD7F5E7)
val forest_light_onTertiaryContainer = Color(0xFF064E3B)
val forest_light_error = Color(0xFFEF4444)
val forest_light_errorContainer = Color(0xFFFFE4E6)
val forest_light_onError = Color(0xFFFFFFFF)
val forest_light_onErrorContainer = Color(0xFF7F1D1D)
val forest_light_background = Color(0xFFF0F8F5)
val forest_light_onBackground = Color(0xFF1F2937)
val forest_light_surface = Color(0xFFFFFFFF)
val forest_light_onSurface = Color(0xFF1F2937)
val forest_light_surfaceVariant = Color(0xFFECFDF5)
val forest_light_onSurfaceVariant = Color(0xFF6B7280)
val forest_light_outline = Color(0xFFD1D5DB)
val forest_light_inverseOnSurface = Color(0xFFF0F8F5)
val forest_light_inverseSurface = Color(0xFF374151)
val forest_light_inversePrimary = Color(0xFF52D98D)
val forest_light_shadow = Color(0xFF000000)
val forest_light_surfaceTint = Color(0xFF2ECC71)
val forest_light_outlineVariant = Color(0xFFE5E7EB)
val forest_light_scrim = Color(0xFF000000)

// Forest Dark
val forest_dark_primary = Color(0xFF52D98D)
val forest_dark_onPrimary = Color(0xFF064E3B)
val forest_dark_primaryContainer = Color(0xFF26B561)
val forest_dark_onPrimaryContainer = Color(0xFFD1FAE5)
val forest_dark_secondary = Color(0xFF5DADE2)
val forest_dark_onSecondary = Color(0xFF1E3A5F)
val forest_dark_secondaryContainer = Color(0xFF2B7BC1)
val forest_dark_onSecondaryContainer = Color(0xFFDBEAFE)
val forest_dark_tertiary = Color(0xFF6EE5A6)
val forest_dark_onTertiary = Color(0xFF064E3B)
val forest_dark_tertiaryContainer = Color(0xFF3DBF75)
val forest_dark_onTertiaryContainer = Color(0xFFD7F5E7)
val forest_dark_error = Color(0xFFFF6B6B)
val forest_dark_errorContainer = Color(0xFFEF4444)
val forest_dark_onError = Color(0xFF7F1D1D)
val forest_dark_onErrorContainer = Color(0xFFFFE4E6)
val forest_dark_background = Color(0xFF0A1612)
val forest_dark_onBackground = Color(0xFFF9FAFB)
val forest_dark_surface = Color(0xFF152822)
val forest_dark_onSurface = Color(0xFFF9FAFB)
val forest_dark_surfaceVariant = Color(0xFF1F3A30)
val forest_dark_onSurfaceVariant = Color(0xFF9CA3AF)
val forest_dark_outline = Color(0xFF6B7280)
val forest_dark_inverseOnSurface = Color(0xFF152822)
val forest_dark_inverseSurface = Color(0xFFF9FAFB)
val forest_dark_inversePrimary = Color(0xFF2ECC71)
val forest_dark_shadow = Color(0xFF000000)
val forest_dark_surfaceTint = Color(0xFF52D98D)
val forest_dark_outlineVariant = Color(0xFF4B5563)
val forest_dark_scrim = Color(0xFF000000)

// ========================================
// OCEAN THEME - Cool Blues/Teals
// ========================================

// Ocean Light
val ocean_light_primary = Color(0xFF1E90FF)
val ocean_light_onPrimary = Color(0xFFFFFFFF)
val ocean_light_primaryContainer = Color(0xFFDBEAFE)
val ocean_light_onPrimaryContainer = Color(0xFF1E3A5F)
val ocean_light_secondary = Color(0xFF20B2AA)
val ocean_light_onSecondary = Color(0xFFFFFFFF)
val ocean_light_secondaryContainer = Color(0xFFCCFBF1)
val ocean_light_onSecondaryContainer = Color(0xFF0F5C56)
val ocean_light_tertiary = Color(0xFF4DB8FF)
val ocean_light_onTertiary = Color(0xFFFFFFFF)
val ocean_light_tertiaryContainer = Color(0xFFE0F2FE)
val ocean_light_onTertiaryContainer = Color(0xFF1E3A5F)
val ocean_light_error = Color(0xFFEF4444)
val ocean_light_errorContainer = Color(0xFFFFE4E6)
val ocean_light_onError = Color(0xFFFFFFFF)
val ocean_light_onErrorContainer = Color(0xFF7F1D1D)
val ocean_light_background = Color(0xFFF0F8FF)
val ocean_light_onBackground = Color(0xFF1F2937)
val ocean_light_surface = Color(0xFFFFFFFF)
val ocean_light_onSurface = Color(0xFF1F2937)
val ocean_light_surfaceVariant = Color(0xFFEFF6FF)
val ocean_light_onSurfaceVariant = Color(0xFF6B7280)
val ocean_light_outline = Color(0xFFD1D5DB)
val ocean_light_inverseOnSurface = Color(0xFFF0F8FF)
val ocean_light_inverseSurface = Color(0xFF374151)
val ocean_light_inversePrimary = Color(0xFF4DB8FF)
val ocean_light_shadow = Color(0xFF000000)
val ocean_light_surfaceTint = Color(0xFF1E90FF)
val ocean_light_outlineVariant = Color(0xFFE5E7EB)
val ocean_light_scrim = Color(0xFF000000)

// Ocean Dark
val ocean_dark_primary = Color(0xFF4DB8FF)
val ocean_dark_onPrimary = Color(0xFF1E3A5F)
val ocean_dark_primaryContainer = Color(0xFF1A7AE0)
val ocean_dark_onPrimaryContainer = Color(0xFFDBEAFE)
val ocean_dark_secondary = Color(0xFF3DD4CC)
val ocean_dark_onSecondary = Color(0xFF0F5C56)
val ocean_dark_secondaryContainer = Color(0xFF1A9991)
val ocean_dark_onSecondaryContainer = Color(0xFFCCFBF1)
val ocean_dark_tertiary = Color(0xFF70C9FF)
val ocean_dark_onTertiary = Color(0xFF1E3A5F)
val ocean_dark_tertiaryContainer = Color(0xFF3AA0E5)
val ocean_dark_onTertiaryContainer = Color(0xFFE0F2FE)
val ocean_dark_error = Color(0xFFFF6B6B)
val ocean_dark_errorContainer = Color(0xFFEF4444)
val ocean_dark_onError = Color(0xFF7F1D1D)
val ocean_dark_onErrorContainer = Color(0xFFFFE4E6)
val ocean_dark_background = Color(0xFF0A1428)
val ocean_dark_onBackground = Color(0xFFF9FAFB)
val ocean_dark_surface = Color(0xFF152238)
val ocean_dark_onSurface = Color(0xFFF9FAFB)
val ocean_dark_surfaceVariant = Color(0xFF1F3548)
val ocean_dark_onSurfaceVariant = Color(0xFF9CA3AF)
val ocean_dark_outline = Color(0xFF6B7280)
val ocean_dark_inverseOnSurface = Color(0xFF152238)
val ocean_dark_inverseSurface = Color(0xFFF9FAFB)
val ocean_dark_inversePrimary = Color(0xFF1E90FF)
val ocean_dark_shadow = Color(0xFF000000)
val ocean_dark_surfaceTint = Color(0xFF4DB8FF)
val ocean_dark_outlineVariant = Color(0xFF4B5563)
val ocean_dark_scrim = Color(0xFF000000)
